# This is a basic workflow to help you get started with Actions

name: Run Tests

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Instalar as dependencias do server
        uses: bahmutov/npm-install@v1
